spring:
  jpa:
    hibernate:
      show_sql: true
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true

  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:

    testWhileIdle: true
    hikari:
      minimumIdle: 1
      maximumPoolSize: ${POOL_MAX_CONNECTIONS:2}
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 200000
      connectionTimeout: 30000
      connection-test-query: SELECT 1

